Build AppImage for Linux
dail8859/NotepadNext pull request #75
Opened 2022-03-09 03:57 UTC by dail8859

This seems to be kind of the minimum changes needed to build an AppImage. The Github action completed successfully and I was able to download a build for Qt6 on an Ubuntu image that doesn't have Qt6 at all...so that's nice. I'm sure there's lots of room for improvement.

2022-03-09 04:05 UTC, dail8859 commented
@FollowerOfBigboss

2022-03-10 01:37 UTC, dail8859 commented
Things that still need addressed:

- [ ] Icons do not seem to work. Only the SVG is deployed with the App image. Probably need to include more sizes/formats. See: https://github.com/mapeditor/tiled/blob/316ceb4dfd5c5bb0ff26c4df885dd1c02d0c92b1/src/tiled/tiled.pro#L562-L604
- [ ] Not overly familiar with .desktop files so might need some improvements. E.g. https://github.com/pbek/QOwnNotes/blob/develop/src/PBE.QOwnNotes.desktop 
- [ ] Should the Notepad Next license be stored in the AppImage somewhere?
- [ ] Update `README.md`
- [ ] Update `doc/Building.md`

2022-03-10 16:16 UTC, FollowerOfBigboss commented
great work @dail8859 . It runs without a problem.

2022-03-12 20:53 UTC, FollowerOfBigboss requested changes
Few corrections.

2022-03-12 20:53 UTC, FollowerOfBigboss commented on doc/Building.md
> +# Linxu
```suggestion
# Linux
```

2022-03-12 20:53 UTC, FollowerOfBigboss commented on doc/Building.md
> +make -j$(nprocs)
```suggestion
make -j$(nproc)
```

2022-03-12 21:22 UTC, dail8859 commented
@FollowerOfBigboss 

> Few corrections.

Good catch! That's what I get for making these changes while being so tired 😊

2022-03-14 23:17 UTC, dail8859 commented
I know there's still work to be done but I think at this point it would be best to just go ahead and get a release version of Linux out to test with and then work through the issues one by one as they come up.

2022-03-14 23:20 UTC, merged